# name: 'sample'
# N: 10
# D: 2
# criterion: [Hinge, MSELoss]
# optimizer: SGD 
# lr: 0.0001
# weight_decay: 0.00001
# epochs: 100
# training_iterations: 3
# batch_size: 4

name: 'sample-beer'
beer: True
N: 10
criterion: Hinge
optimizer: SGD 
lr: 0.0001
weight_decay: 0.00001
epochs: 100
training_iterations: 3
batch_size: 4